# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.18.6
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=1.0.9
maven_group=me.percydan
archives_base_name=BorderRemover

# Dependencies
fabric_api_version=0.141.3+1.21.11